requires = ["tox>=4"]
env_list = ["3.15", "3.14", "3.13", "3.12", "3.11", "3.10", "3.9"]

[env_run_base]
description = "Run unit tests across Python environments"
skip_missing_interpreters = true

package = "wheel"
wheel_build_env = ".pkg"

changedir = "{tox_root}/test"
commands= [
    ["python3", "-m", "unittest", "discover"]
]
