name: CI

on:
  workflow_dispatch:
    inputs:
      upload-wheel:
        type: boolean
        required: false
        default: false
        description: Upload wheel as an artifact
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/step_test.yaml

  build-wheel:
    uses: ./.github/workflows/step_build-wheel.yaml
    needs: [ tests ]
    with:
      upload: ${{ inputs.upload-wheel || false }}
  pass:
    needs: [tests, build-wheel]
    runs-on: ubuntu-latest
    steps:
      - name: Check all CI action
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
